#!/usr/bin/env node
// PRD-WIRE S4 — dev/CI seeder. Drives N example DRAFTS end-to-end through the
// REAL ingest API (the §4.2 routes + §4.3 verification gate — nothing is ever
// inserted behind the validator's back): boots mountWire on an ephemeral
// localhost port against DATABASE_URL, POSTs the drafts over real HTTP,
// optionally flips them live through the real publish call, then exits.
//
// NOT a prod path, by construction:
//   - standalone bin + test import only — server.js never touches it, and it
//     is not in the unguarded npm-test chain;
//   - refuses a non-local DATABASE_URL unless --allow-remote-db is passed,
//     so a production database is never seeded by accident;
//   - deterministic seed-example-* postIds/slugs — re-runs REPLACE the drafts
//     (US-W4 idempotency, exercised on every run) instead of piling up rows;
//   - every seed is visibly synthetic ("Seed example: …" titles, example.com/
//     example.org sources) — even a mistaken publish could never read as news.
//
// Usage:
//   DATABASE_URL=postgres://…@localhost/db npm run seed-wire [-- --count 5 --publish]
//   Flags: --count N (default 3, max 25) · --publish (flip drafts live via
//   the publish call) · --allow-remote-db (explicit non-local override)
import express from "express";
import { createServer } from "http";
import { pathToFileURL } from "url";
import pg from "pg";
import { mountWire } from "../server/wire/index.js";
import { WIRE_TYPES, FACTUAL_TYPES } from "../server/wire/validate.js";

const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "::1", "[::1]"]);

/** Pure guard, exported for tests: throws unless DATABASE_URL points at a
 *  local host (or the caller explicitly allowed remote). */
export function assertLocalDatabase(databaseUrl, allowRemote = false) {
  if (!databaseUrl) throw new Error("[seed-wire] DATABASE_URL is required");
  let host;
  try { host = new URL(databaseUrl).hostname; } catch (_) {
    throw new Error("[seed-wire] DATABASE_URL is not a parseable URL");
  }
  if (!allowRemote && !LOCAL_HOSTS.has(host)) {
    throw new Error(
      `[seed-wire] refusing to seed a non-local database (host '${host}') — ` +
      "this script is for local/CI databases only; pass --allow-remote-db if you really mean it",
    );
  }
}

/** N example posts cycling the five types, every one of which passes the
 *  §4.3 gate: factual types carry two sources on independent registrable
 *  domains (example.com / example.org — RFC 2606 reserved, unmistakably
 *  synthetic), first-party types carry one canonical-artifact-style source. */
export function buildSeedPosts(count, nowMs = Date.now()) {
  const retrievedAt = new Date(nowMs - 3_600_000).toISOString();
  const src = (url, title, claims) => ({ url, title, retrievedAt, claims });
  return Array.from({ length: count }, (_, i) => {
    const type = WIRE_TYPES[i % WIRE_TYPES.length];
    const n = i + 1;
    const sources = FACTUAL_TYPES.includes(type)
      ? [
          src(`https://example.com/announcements/${n}`, `Example vendor announcement ${n}`, `Seed claim ${n}a — the announced figure`),
          src(`https://example.org/coverage/${n}`, `Example independent coverage ${n}`, `Seed claim ${n}b — the corroborating report`),
        ]
      : [src(`https://example.com/artifacts/${n}`, `Example canonical artifact ${n}`, `Seed claim ${n} — the artifact this post reports`)];
    return {
      postId: `seed-example-${n}`,
      slug: `seed-example-${n}`,
      type,
      tags: ["seed", type],
      title: `Seed example ${n}: a ${type} post for tests and dev`,
      summary: `Synthetic Wire post ${n} of ${count}, generated by scripts/seed-wire.mjs. Not news — a fixture exercising the real ingest contract end to end.`,
      bodyMd: `This is **seed content** posted through the real \`POST /api/wire/posts\` route.\n\n- type: ${type}\n- run: seed-example-${n}\n\nRe-running the seeder replaces this draft in place ([idempotency on postId](https://example.com/contract)).`,
      sources,
      byline: { agents: ["seed-wire"], missionRun: `seed-example-${n}`, model: "none-fixture" },
    };
  });
}

/**
 * Boot the real wire module on 127.0.0.1:0, POST `count` drafts through real
 * HTTP, optionally publish each, clean up, and return per-post results:
 * `[{postId, slug, status, ok, published, error}]`. Review publish-policy
 * always — even `--publish` exercises the two-step draft → publish flow the
 * D-W1 launch mode uses.
 */
export async function seedWire({ databaseUrl, count = 3, publish = false, key = "wk_seed_local_only", allowRemote = false } = {}) {
  assertLocalDatabase(databaseUrl, allowRemote);
  if (!Number.isInteger(count) || count < 1 || count > 25) {
    throw new Error("[seed-wire] count must be an integer 1..25");
  }
  const pool = new pg.Pool({ connectionString: databaseUrl, max: 3 });
  const app = express();
  app.use(express.json({ limit: "1mb" }));
  mountWire(app, { pool, ingestKey: key, publishPolicy: "review", rateLimit: { max: 10_000, windowMs: 60_000 } });
  const server = createServer(app);
  await new Promise((r) => server.listen(0, "127.0.0.1", r));
  const base = `http://127.0.0.1:${server.address().port}`;
  const results = [];
  try {
    for (const post of buildSeedPosts(count)) {
      const res = await fetch(`${base}/api/wire/posts`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-Wire-Key": key },
        body: JSON.stringify(post),
      });
      const body = await res.json();
      let published = false;
      if (publish && res.ok) {
        const p = await fetch(`${base}/api/wire/posts/${encodeURIComponent(post.postId)}/publish`, {
          method: "POST", headers: { "X-Wire-Key": key },
        });
        published = p.ok;
      }
      results.push({ postId: post.postId, slug: post.slug, status: res.status, ok: res.ok, published, error: res.ok ? null : body });
    }
  } finally {
    server.close();
    await pool.end();
  }
  return results;
}

// ── standalone bin ──────────────────────────────────────────────────────
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = process.argv.slice(2);
  const countIdx = args.indexOf("--count");
  const count = countIdx === -1 ? 3 : Number(args[countIdx + 1]);
  try {
    const results = await seedWire({
      databaseUrl: process.env.DATABASE_URL,
      count,
      publish: args.includes("--publish"),
      key: process.env.WIRE_INGEST_KEY || "wk_seed_local_only",
      allowRemote: args.includes("--allow-remote-db"),
    });
    let hard = 0;
    for (const r of results) {
      if (r.ok) console.log(`  ✓ ${r.postId} → ${r.status}${r.published ? " + published" : " (draft)"}`);
      else if (r.status === 409) console.warn(`  • ${r.postId} → 409 ${r.error.reason} (published by an earlier seed run — immutable, as designed)`);
      else { hard++; console.error(`  ✗ ${r.postId} → ${r.status} ${JSON.stringify(r.error)}`); }
    }
    console.log(`[seed-wire] ${results.length} posts driven through the real API`);
    process.exit(hard ? 1 : 0);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
